# Generated by Django 5.2 on 2026-03-26 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('gym', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('court', models.BooleanField(default=False)),
                ('parks', models.BooleanField(default=False)),
                ('party_spaces', models.BooleanField(default=False)),
                ('concierge', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoomsExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('living_room', models.BooleanField(default=True)),
                ('garden', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=True)),
                ('laundry_room', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('office', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_purpose', models.CharField(choices=[('S', 'Sale'), ('R', 'Rent'), ('B', 'Both')], max_length=1)),
                ('type', models.CharField(choices=[('A', 'Apartment'), ('H', 'House')], max_length=1)),
                ('area', models.FloatField()),
                ('floors', models.IntegerField()),
                ('floor_number', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('address', models.TextField(max_length=200)),
                ('neighborhood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('has_mobilia', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('embedding', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.condo')),
            ],
        ),
        migrations.CreateModel(
            name='PropertiesPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r2_key', models.TextField()),
                ('order', models.IntegerField()),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.properties')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('parking_spots', models.IntegerField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bedrooms', 'bathrooms', 'parking_spots'), name='rooms_unique')],
            },
        ),
        migrations.AddField(
            model_name='properties',
            name='rooms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.rooms'),
        ),
        migrations.AddField(
            model_name='properties',
            name='rooms_extras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.roomsextras'),
        ),
    ]
