# Generated by Django 5.2 on 2026-03-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertiesphotos',
            old_name='property_id',
            new_name='property',
        ),
    ]
