# Generated by Django 5.2 on 2026-04-23 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_properties_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='rooms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.rooms'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='rooms_extras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.roomsextras'),
        ),
    ]
