# Generated by Django 5.2 on 2026-04-23 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_properties_rooms_alter_properties_rooms_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='rooms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.rooms'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='rooms_extras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.roomsextras'),
        ),
    ]
