# Generated by Django 5.2 on 2026-03-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="searchpreference",
            name="max_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="searchpreference",
            name="min_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="searchpreference",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[("H", "House"), ("A", "Apartment")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("A", "Advertiser"), ("S", "Seeker")],
                db_index=True,
                default="S",
                max_length=1,
            ),
        ),
    ]
